### ISSUE TITLE
How would one go about installing this?

### ISSUE THREAD

**Issue by illegitimate-egg** [skearya/dots#3]
I really like how it looks but can't work out how to install it?

**Comment by Barquadd** [comment]
If you already have all the proper software installed, you should be able to copy the files from skeary's [.config](https://github.com/skearya/dots/tree/v2/.config) to your local ``~/.config`` stored on your computer.

**Comment by illegitimate-egg** [comment]
What software do I need to have installed (sorry for the dumb question)

**Comment by Barquadd** [comment]
No worries!

Quoting the README in the repo, 
>- **Window Manager**: [bspwm](https://github.com/baskerville/bspwm)
>- **Terminal:** [alacritty](https://github.com/alacritty/alacritty)
>- **Compositor:** [picom-jonaburg-git](https://github.com/jonaburg/picom)
>- **Application Launcher:** [rofi](https://github.com/davatorium/rofi)
>- **Dock:** [Plank](https://launchpad.net/plank)
>- **Wallpaper:** [Quixotic Wallpapers](https://github.com/QuixoticCS/quixotic-wallpaper)
>- **GTK:** [Awesthetic](https://github.com/saimoomedits/dotfiles/blob/main/extras/themes)
>- **Fonts:** JetBrains Mono Nerd Font, Material Design Icons, Product Sans
>- **Icon Theme:** [Quixotic-SEv2](https://github.com/QuixoticCS/quixotic-icons)

This should be everything important that you need to install.

**Comment by illegitimate-egg** [comment]
I've done all of that, now what?

**Comment by Barquadd** [comment]
You should be able to now copy over the [files from the repo](https://github.com/skearya/dots/tree/v2/.config) to the appropriate location in your ``~/.config`` directory.

**Comment by illegitimate-egg** [comment]
And then? :))))

**Comment by Barquadd** [comment]
Logout of your computer and then log back in, or, restart it, that should make the software use the programs.

**Comment by illegitimate-egg** [comment]
It looks the same? ![th](https://cdn.discordapp.com/attachments/731199530027974698/1011959567934034000/VirtualBox_Endeavour_OS_24_08_2022_12_25_26.png)
Btw my discord is: `illegitimate-egg#6969`

**Comment by illegitimate-egg** [comment]
uh oh, I tried copying the files again and now the desktop isn't loading

**Comment by skearya** [comment]
person helped in dms btw :)
